# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = ["hugo-embed-pdf-shortcode", "blowfish"]
baseURL = "https://teiboku.github.io/"
defaultContentLanguage = "ja"

enableRobotsTXT = true
[pagination]
  pagerSize = 10
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true
enableInlineShortcodes = true
[services]
  [services.googleAnalytics]
    id = 'G-81CKDRV36F'


[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
