languageCode = "ja"
languageName = "日本語"
weight = 1

title = "かんそう"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  description = "Home Page of GUAN CONG."
  dateFormat = "2006年1月2日"

[params.author]
  name = "GUAN　CONG"
  image = "goubao.jpg"
  headline = """

  """
  bio = "早稲田大学でコンピュータサイエンスを学んでいる学生です。機械学習、自然言語処理、コンピュータビジョンに興味があります。"
  links = [
    
  ]
  