languageCode = "ja"
languageName = "日本語"
weight = 1

title = "かんそう"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  description = "Home Page of GUAN CONG."
  dateFormat = "2006年1月2日"

[params.author]
  name = "かん そう"
  image = "goubao.jpg"
  headline = """
  私の名前「GUAN CONG」は日本語で「感想」と読みます。 
  感想とは印象や思考を意味します。 
  人生でより多くの経験を積み、思い出や感情を作り、学び、
  楽しみ、充実した生活を送りたいと思います。
  
  現在は、計算写真学、画像・動画生成、超解像、拡散モデルなどの研究に取り組んでいます。
カメラとAIの融合による新しい表現や体験を創り出すことに情熱を持っています。

  2026年12月に博士課程の修了を予定しており、日本国内でアルゴリズムエンジニアとしてのキャリア機会を探しております。

  私のホームページにお越しいただき、ありがとうございます。
  """
  bio = "早稲田大学でコンピュータサイエンスを学んでいる学生です。機械学習、自然言語処理、コンピュータビジョンに興味があります。"
  links = [
    
  ]
  