[[main]]
name = "ブログ"
pageRef = "posts"
weight = 1





[[main]]
name = "プロジェクト"
pageRef = "projects"
weight = 2


[[main]]
name = "職務経歴書"
pageRef = "resume"
weight = 3

[[main]]
name = "自己紹介"
pageRef = "about"
weight = 4

[[footer]]
none = "none"
