colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
disableImageOptimization = false
defaultBackground = "nujabes.jpg"
enableSearch = true
enableCodeCopy = true

[header]
layout = "hero"

[footer]
showCopyright = false
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true
showMenu = false

[homepage]
layout = "background"
homepageImage = "nujabes.png"
showRecent = false
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "big"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email" ]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]

[pagination]
pagerSize = 10
